version: "3"

services:
  cihm-cantaloupe:
    build: .
    image: cihm-cantaloupe:latest
    ports:
      - "8182:8182"
    # environment:
    # - S3SOURCE_ENDPOINT=https://swifts3.endpoint/
    # - S3SOURCE_ACCESS_KEY_ID=swiftuser
    # - S3SOURCE_SECRET_KEY=swifts3secret
    # - S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME=test
    # - JWT_ISSUER=CAP
    # - JWT_SECRET=capjwtsecret
